
//===============USER APIS======================
//These are apis available at http(s)://DOMAIN(:PORT)/user/


//user login
POST http://localhost:3000/user/login http/1.1
content-type: application/json

{
    "email": "rconnect250@gmail.com",
    "password": "123456"
}

###

//user register
POST http://localhost:3000/user/register http/1.1
Content-Type: application/json

{
    "full_name": "Harerimana Egide",
    "display_name": "egide",
    "email": "egideharerimana085@gmail.com",
    "password": "123456"
}

###

//verify token on page load
GET http://localhost:3000/user/verify-token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWZlYzg5YTYyOTQ1NDAxMmY4NTJlOGE2Iiwid29ya3NwYWNlX2lkIjoiIiwiaWF0IjoxNjEwMzgzOTYzfQ.SqCUCCKS2IP0qV4aWwB0aDttTl8BAUZdP37Gkl2KWL4 http/1.1
Content-Type: application/json

###

//send email verification code 
POST http://localhost:3000/user/verify_email http/1.1
Content-Type: application/json

{
    "full_name": "Harerimana Egide",
    "email": "egideharerimana085@gmail.com"
}

###

//Check if email is registered or used
GET http://localhost:3000/user/check-email-taken/rconnect250@gmail.com
Content-Type: application/json

###
